Improved and refactored admin part frontend javascript into a mini li…
fistodul/nekretnine pull request #3
Opened 2022-12-19 14:20 UTC by AWackO

2022-12-19 15:45 UTC, filipopo requested changes

2022-12-19 15:45 UTC, filipopo commented on views/admin.ejs
> +    el.appendChild( document.createTextNode(" "));
Daj obrisi ovaj space

2022-12-19 15:45 UTC, filipopo commented on views/admin.ejs
>      temp.appendChild(temp2);
Ne valja ovo, makeEl treba da bude umesto temp2, sad appenduje stari temp2 2 puta

2022-12-19 15:45 UTC, filipopo commented on views/admin.ejs
>      temp.appendChild(temp2);
prebaci ovo iznad u ovo

2022-12-19 15:45 UTC, Filip98 commented on views/admin_dodajstan.ejs
> +  }idStr= 4
???

2022-12-19 15:45 UTC, Filip98 commented on views/admin_dodajstan.ejs
>      el.parentNode.insertBefore(temp, el);
Mozes da prebacis iz temp u funkciju dole ispod ali da razdelis sa new lines, idk use your discretion

2022-12-19 15:45 UTC, Filip98 commented on views/admin_dodajstan.ejs
>      insertAfter(el, temp);
nalepi dole

2022-12-19 15:45 UTC, filipopo commented on views/admin_dodajstan.ejs
>      el = "Dodaj oglas";
daj obrisi new line ovde

2022-12-19 15:59 UTC, AWackO commented on views/admin.ejs
>      temp.appendChild(temp2);
temp.appendChild(makeEl("button", {type:"button", innerHTML:"-"}, () => {
       el.parentNode.removeChild(el);
     }););
Ovako?

2022-12-19 16:02 UTC, AWackO commented on views/admin.ejs
>      temp.appendChild(temp2);
Sta u sta xd?
Ovo:  const el = document.createElement("div");
U:  const el = makeEl("div");?

2022-12-19 16:03 UTC, AWackO commented on views/admin_dodajstan.ejs
>      el.parentNode.insertBefore(temp, el);
Mislis da ce mnogo chaotic da bude?

2022-12-19 16:04 UTC, AWackO commented on views/admin_dodajstan.ejs
>      insertAfter(el, temp);
Mislis da budu jedan line do drugog?
ovako:
el = makeEl("input", {name:"vrednost" + p_id, type:"text", maxLength:"25", placeholder:"Vrednost"});
insertAfter(el, temp);
insertAfter(document.createElement("br"), el);

2022-12-19 16:11 UTC, Filip98 commented on views/admin.ejs
>      temp.appendChild(temp2);
Pa da, 262 - 264 umesto temp2 u 266, trenutno se nista ne radi da returned elementom

2022-12-19 16:13 UTC, Filip98 commented on views/admin.ejs
>      temp.appendChild(temp2);
ne be, temp2 s 246 u liniju ispod

2022-12-19 16:13 UTC, Filip98 commented on views/admin_dodajstan.ejs
>      el.parentNode.insertBefore(temp, el);
doro ne mora

2022-12-19 16:15 UTC, AWackO commented on views/admin.ejs
>      temp.appendChild(temp2);
temp.appendChild(document.createElement("span"););
    temp.appendChild(document.createTextNode(" "););
Ovo?

2022-12-20 10:11 UTC, Filip98 commented
Invalidated by #5 ...

2022-12-20 10:11 UTC, closed without merging